# Generated by Django 4.2.3 on 2023-10-18 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=255)),
                ('configuration_details', models.JSONField(default=dict)),
                ('connection_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('type', models.JSONField(default=dict)),
                ('api_keys', models.JSONField(default=dict)),
                ('configuration_details', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='MachineLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('algorithm', models.CharField(choices=[('svm', 'Support Vector Machine'), ('rf', 'Random Forest')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('last_trained_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('accuracy', models.FloatField(default=0.0)),
                ('resource_efficiency', models.FloatField(default=0.0)),
                ('sustainability_score', models.FloatField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('sensor_data_reference', models.CharField(max_length=255)),
                ('training_data_reference', models.TextField(default='')),
                ('is_real_time', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('testing', 'Testing')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(choices=[('new_nihilist', 'New Nihilist'), ('pioneer', 'Pioneer'), ('time_keeper', 'Time Keeper'), ('reductionist', 'Reductionist'), ('dreamer', 'Dreamer'), ('rebel', 'Rebel'), ('maestro', 'Maestro'), ('builder', 'Builder'), ('entity', 'Entity'), ('crusader', 'Crusader')], default='new_nihilist', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('preferences', models.JSONField(default=dict)),
                ('subscription_details', models.JSONField(default=dict)),
                ('psychographics', models.TextField(blank=True)),
                ('needs_pain_points', models.TextField(blank=True)),
                ('goals_dreams', models.TextField(blank=True)),
                ('universal_themes', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('space_type', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=100)),
                ('configuration', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(max_length=40)),
                ('data', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letsbright.device')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('shipping_address', models.TextField(default='')),
                ('Device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letsbright.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gamification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('badges', models.JSONField(default=dict)),
                ('challenges_completed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_details', models.TextField(default='')),
                ('rating', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(upload_to='designs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=255)),
                ('content_details', models.TextField(default='')),
                ('associated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
